import { ClerkProvider } from "@clerk/nextjs";
import "../global.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  robots: {
    index: false,
    follow: false,
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ClerkProvider>
  )
}
